version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo 배포 모듈 설치중..test
  pre_build:
    commands:
      - echo 의존성 설치중...
  build:
    commands:
      - echo Build started on `date`
  post_build:
    commands:
      - echo Build completed on `date`